### ISSUE TITLE
Please demo project with java😢

### ISSUE THREAD

**Issue by AungSiMin-007** [krossovochkin/DynamicChangeThemeSample#1]

**Comment by krossovochkin** [comment]
Hi,

Sorry, I don't have plans to create separate project in Java.
I guess if you're not comfortable with Kotlin, then you can try to "convert" sources to Java with something like [this](https://stackoverflow.com/a/40762755/1533933)

There is nothing really Kotlin specific in this repository.
And probably it is anyway good time to start learning Kotlin.

Thanks for your understanding

PS: this repository has a demo project, which one should take as an inspiration. It is anyway not a production ready
